hugo:
  image:
    # https://docker.hugomods.com
    name: ghcr.io/hugomods/hugo:base
  script: "./hugo.sh"
  artifacts:
    paths:
    - build/public

lychee:
  image:
    # https://lychee.cli.rs/docker
    name: docker.io/lycheeverse/lychee:latest-alpine
    entrypoint: [""] # force an empty entrypoint
  script: "lychee --offline ./content"
